# Generated by Django 3.1.2 on 2020-10-16 14:16

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='brief',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
